name: publish
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  ACTOR: ${{ github.actor }}
jobs:
  publish:
    name: publish images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [web, server]
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish ${{ matrix.app }} Application
        run: |
          docker build ./${{ matrix.app }} --tag ${{ env.REGISTRY }}/${{ env.ACTOR }}/shelf-${{ matrix.app }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.ACTOR }}/shelf-${{ matrix.app }}:latest
